"""adding additional info field

Revision ID: V12
Revises: V11
Create Date: 2024-06-27 08:36:02.646270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'V12'
down_revision: Union[str, None] = 'V11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_history', sa.Column('additional_information', sqlmodel.sql.sqltypes.AutoString(), nullable=True), schema='py_api')
    op.add_column('alerts', sa.Column('additional_information', sqlmodel.sql.sqltypes.AutoString(), nullable=True), schema='py_api')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'additional_information', schema='py_api')
    op.drop_column('alert_history', 'additional_information', schema='py_api')
    # ### end Alembic commands ###
