"""first migration

Revision ID: V1
Revises: 
Create Date: 2023-12-25 13:45:21.531020

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.

revision: str = 'V2'
down_revision: str = 'V1'

branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subbasins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sub_basin_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='py_api'
    )
    op.create_table('basins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('basin_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subbasins_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subbasins_id'], ['py_api.subbasins.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='py_api'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('basins', schema='py_api')
    op.drop_table('subbasins', schema='py_api')
    # ### end Alembic commands ###
