"""add basin data

Revision ID: V3
Revises: V2
Create Date: 2023-12-25 14:02:25.016487

"""
import json
import logging
import os
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

LOGGER = logging.getLogger(__name__)

# revision identifiers, used by Alembic.
revision: str = 'V3'
down_revision: Union[str, None] = 'V2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

schema = 'py_api'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # loading the basins data
    basin_file = os.path.join(os.path.dirname(__file__), '..', 'data', "basins.json")
    LOGGER.debug(f"src file: {basin_file}")

    with open(basin_file, "r") as json_file:
        basins_data = json.load(json_file)

    for basin in basins_data:
        basin_name_str = basin["basin_name"]
        op.execute(f'INSERT INTO {schema}.basins(basin_name) VALUES (\'{basin_name_str}\')')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"delete from {schema}.basins")
    pass
    # ### end Alembic commands ###
