"""adding alert tables

Revision ID: V4
Revises: V3
Create Date: 2024-01-26 20:51:07.534244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'V4'
down_revision: Union[str, None] = 'V3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_levels',
    sa.Column('alert_level_id', sa.Integer(), nullable=False),
    sa.Column('alert_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('alert_level_id'),
    schema='py_api'
    )
    op.create_table('alerts',
    sa.Column('alert_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('alert_hydro_conditions', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('alert_meteorological_conditions', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('basin_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['basin_id'], ['py_api.basins.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='py_api'
    )
    op.create_table('alert_areas',
    sa.Column('alert_area_id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('basin_id', sa.Integer(), nullable=False),
    sa.Column('alert_level_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['py_api.alerts.id'], ),
    sa.ForeignKeyConstraint(['alert_level_id'], ['py_api.alert_levels.alert_level_id'], ),
    sa.ForeignKeyConstraint(['basin_id'], ['py_api.basins.id'], ),
    sa.PrimaryKeyConstraint('alert_area_id'),
    schema='py_api'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert_areas', schema='py_api')
    op.drop_table('alerts', schema='py_api')
    op.drop_table('alert_levels', schema='py_api')
    # ### end Alembic commands ###
