"""Add CAP Event relationships

Revision ID: V9
Revises: V8
Create Date: 2024-04-23 10:23:19.036230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'V9'
down_revision: Union[str, None] = 'V8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'alert_area_history', ['alert_history_id', 'basin_id', 'alert_level_id'], schema='py_api')
    op.create_foreign_key(None, 'alert_area_history', 'alert_history', ['alert_history_id'], ['alert_history_id'], source_schema='py_api', referent_schema='py_api')
    op.add_column('cap_event_areas', sa.Column('cap_event_id', sa.Integer(), nullable=False), schema='py_api')
    op.create_foreign_key(None, 'cap_event_areas', 'cap_event', ['cap_event_id'], ['cap_event_id'], source_schema='py_api', referent_schema='py_api')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cap_event_areas', schema='py_api', type_='foreignkey')
    op.drop_column('cap_event_areas', 'cap_event_id', schema='py_api')
    op.drop_constraint(None, 'alert_area_history', schema='py_api', type_='foreignkey')
    op.drop_constraint(None, 'alert_area_history', schema='py_api', type_='unique')
    # ### end Alembic commands ###
